import type { Product } from "./types"

export const categories = [
  { id: "wadah-tisu", name: "Wadah Tisu", icon: "🧻" },
  { id: "mangkok", name: "Mangkok", icon: "🥣" },
  { id: "panci", name: "Panci", icon: "🍲" },
  { id: "tutup-makanan", name: "Tutup Makanan", icon: "🍽️" },
  { id: "cangkir", name: "Cangkir", icon: "☕" },
  { id: "sendok-garpu", name: "Sendok & Garpu", icon: "🍴" },
  { id: "ring-adonan", name: "Ring Adonan", icon: "⭕" },
  { id: "telenan", name: "Telenan", icon: "🔪" },
  { id: "toples", name: "Toples", icon: "🫙" },
  { id: "rolling-pin", name: "Rolling Pin", icon: "🥖" },
]

export const products: Product[] = [
  // Featured Products
  {
    id: "1",
    name: "Kotak Makanan Premium Set",
    price: 125000,
    originalPrice: 150000,
    image: "/placeholder.svg?height=300&width=300",
    category: "kotak-makanan",
    description: "Set kotak makanan premium dengan 5 ukuran berbeda, tahan panas dan dingin, BPA free",
    featured: true,
    inStock: true,
    rating: 4.8,
    reviews: 124,
  },
  {
    id: "2",
    name: "Lunch Set Elegant",
    price: 89000,
    originalPrice: 110000,
    image: "/placeholder.svg?height=300&width=300",
    category: "lunch-set",
    description: "Lunch set lengkap dengan tas isolasi, sendok garpu, dan tempat minum",
    featured: true,
    inStock: true,
    rating: 4.7,
    reviews: 89,
  },
  {
    id: "3",
    name: "Mangkok Kristal Luxury",
    price: 75000,
    image: "/placeholder.svg?height=300&width=300",
    category: "mangkok",
    description: "Mangkok kristal berkualitas tinggi, cocok untuk hidangan istimewa",
    featured: true,
    inStock: true,
    rating: 4.9,
    reviews: 156,
  },
  {
    id: "4",
    name: "Eco Botol Ramah Lingkungan",
    price: 45000,
    originalPrice: 55000,
    image: "/placeholder.svg?height=300&width=300",
    category: "eco-botol",
    description: "Botol minum eco-friendly, tahan panas, kapasitas 500ml",
    featured: true,
    inStock: true,
    rating: 4.6,
    reviews: 203,
  },
  {
    id: "5",
    name: "Cannister Set Modern",
    price: 95000,
    image: "/placeholder.svg?height=300&width=300",
    category: "cannister",
    description: "Set 3 cannister modern untuk penyimpanan bahan makanan kering",
    featured: true,
    inStock: true,
    rating: 4.8,
    reviews: 67,
  },

  // Category Products
  {
    id: "6",
    name: "Wadah Tisu Kayu Premium",
    price: 35000,
    image: "/placeholder.svg?height=300&width=300",
    category: "wadah-tisu",
    description: "Wadah tisu dari kayu berkualitas dengan desain minimalis",
    inStock: true,
    rating: 4.5,
    reviews: 45,
  },
  {
    id: "7",
    name: "Mangkok Keramik Set 6pcs",
    price: 120000,
    originalPrice: 140000,
    image: "/placeholder.svg?height=300&width=300",
    category: "mangkok",
    description: "Set 6 mangkok keramik dengan berbagai ukuran",
    inStock: true,
    rating: 4.7,
    reviews: 78,
  },
  {
    id: "8",
    name: "Panci Anti Lengket 24cm",
    price: 185000,
    image: "/placeholder.svg?height=300&width=300",
    category: "panci",
    description: "Panci anti lengket dengan lapisan ceramic coating",
    inStock: true,
    rating: 4.8,
    reviews: 92,
  },
  {
    id: "9",
    name: "Tutup Makanan Silikon Fleksibel",
    price: 25000,
    image: "/placeholder.svg?height=300&width=300",
    category: "tutup-makanan",
    description: "Set tutup makanan silikon yang dapat meregang",
    inStock: true,
    rating: 4.4,
    reviews: 134,
  },
  {
    id: "10",
    name: "Cangkir Kopi Keramik Premium",
    price: 55000,
    image: "/placeholder.svg?height=300&width=300",
    category: "cangkir",
    description: "Cangkir kopi keramik dengan desain elegan",
    inStock: true,
    rating: 4.6,
    reviews: 67,
  },
  {
    id: "11",
    name: "Set Sendok Garpu Stainless Steel",
    price: 65000,
    image: "/placeholder.svg?height=300&width=300",
    category: "sendok-garpu",
    description: "Set lengkap sendok garpu dari stainless steel food grade",
    inStock: true,
    rating: 4.7,
    reviews: 89,
  },
  {
    id: "12",
    name: "Ring Adonan Adjustable",
    price: 40000,
    image: "/placeholder.svg?height=300&width=300",
    category: "ring-adonan",
    description: "Ring adonan yang dapat disesuaikan ukurannya",
    inStock: true,
    rating: 4.5,
    reviews: 34,
  },
  {
    id: "13",
    name: "Telenan Bambu Antibakteri",
    price: 45000,
    image: "/placeholder.svg?height=300&width=300",
    category: "telenan",
    description: "Telenan bambu dengan sifat antibakteri alami",
    inStock: true,
    rating: 4.8,
    reviews: 156,
  },
  {
    id: "14",
    name: "Toples Kaca Hermetis 1L",
    price: 35000,
    image: "/placeholder.svg?height=300&width=300",
    category: "toples",
    description: "Toples kaca dengan penutup hermetis, kapasitas 1 liter",
    inStock: true,
    rating: 4.6,
    reviews: 78,
  },
  {
    id: "15",
    name: "Rolling Pin Kayu Solid",
    price: 30000,
    image: "/placeholder.svg?height=300&width=300",
    category: "rolling-pin",
    description: "Rolling pin dari kayu solid untuk menggulung adonan",
    inStock: true,
    rating: 4.7,
    reviews: 45,
  },
]

export const getProductsByCategory = (category: string) => {
  return products.filter((product) => product.category === category)
}

export const getFeaturedProducts = () => {
  return products.filter((product) => product.featured)
}

export const getProductById = (id: string) => {
  return products.find((product) => product.id === id)
}
